# options for analysis running
run:
  timeout: 3m
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    # Default set of linters from golangci-lint
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck


