project_name: stash
before:
  hooks:
    - go mod download
builds:
  - binary: stash-win
    ldflags:
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -tags
      - extended
    goos:
      - windows
    goarch:
      - amd64
  - binary: stash-osx
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -tags
      - extended
    goos:
      - darwin
    goarch:
      - amd64
  - binary: stash-osx-applesilicon
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -tags
      - extended
    goos:
      - darwin
    goarch:
      - arm64
  - binary: stash-linux
    env:
      - CGO_ENABLED=1
    flags:
      - -tags
      - extended
    goos:
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  files:
    - README.md
    - LICENSE
release:
  draft: true